from PyQt5 import QtGui
from app.db.models import Stars
from PyQt5 import QtCore, QtWidgets
from PyQt5.QtWidgets import  QWidget
from app.db.models import session

class stars(QWidget):
    model = Stars
    id = 1
    seriesList = [
        {
            'name':"test",
            'avatar': "C:/Users/DeadlyComputer/Desktop/photo/578211-gettyimages-542930526.jpg",
            'movies': [
                "fajny  ",
                "fajny2",
                "fajny3",
                "fajny5",
                'fajny6'
            ]
        }
    ]
    def __init__(self,):
        super().__init__()

    def getOne(self):
        self.data=session.query(self.model).get(self.id)

    def show(self):
        self.getOne()
        self.setupUi()
        self.obj.show()

    def createObj(self):
        self.obj = QtWidgets.QMainWindow()
        self.obj.setObjectName("StarList")
        self.obj.resize(1707, 1036)

    def avatar(self):
        self.label = QtWidgets.QLabel(self.obj)
        self.label.setGeometry(QtCore.QRect(100, 80, 341, 331))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(self.data.avatar))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")

    def title(self):
        self.Title = QtWidgets.QLabel(self.obj)
        self.Title.setGeometry(QtCore.QRect(530, 60, 391, 91))
        self.Title.setObjectName("Title")
        self.Title.setToolTip("<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-style:italic;\">"+self.data.name+"</span></p></body></html>")
        self.Title.setText("<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600; text-decoration: underline;\">"+self.data.name+"</span></p></body></html>")

    def galery(self):
        photos=self.data.photos
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.obj)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(1040, 50, 581, 361))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")

        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        row=0
        col=0
        for photo in photos:
            label = QtWidgets.QLabel(self.gridLayoutWidget_2)
            label.setMaximumSize(QtCore.QSize(100, 100))
            label.setText("")
            label.setPixmap(QtGui.QPixmap(photo.src))
            label.setScaledContents(True)
            label.setObjectName("label_9")
            self.gridLayout_5.addWidget(label, col, row, 1, 1)
            row=row+1
            if row > 3:
                row=0
                col=col+1

        """"
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.obj)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(1040, 50, 581, 361))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_9.setMaximumSize(QtCore.QSize(100, 100))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("C:/Users/DeadlyComputer/Desktop/photo/578211-gettyimages-542930526.jpg"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.gridLayout_5.addWidget(self.label_9, 0, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_20.setMaximumSize(QtCore.QSize(100, 100))
        self.label_20.setText("")
        self.label_20.setPixmap(QtGui.QPixmap("C:/Users/DeadlyComputer/Desktop/photo/578211-gettyimages-542930526.jpg"))
        self.label_20.setScaledContents(True)
        self.label_20.setObjectName("label_20")
        self.gridLayout_5.addWidget(self.label_20, 0, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_12.setMaximumSize(QtCore.QSize(100, 100))
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap("C:/Users/DeadlyComputer/Desktop/photo/578211-gettyimages-542930526.jpg"))
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName("label_12")
        self.gridLayout_5.addWidget(self.label_12, 0, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_21.setMaximumSize(QtCore.QSize(100, 100))
        self.label_21.setText("")
        self.label_21.setPixmap(QtGui.QPixmap("C:/Users/DeadlyComputer/Desktop/photo/578211-gettyimages-542930526.jpg"))
        self.label_21.setScaledContents(True)
        self.label_21.setObjectName("label_21")
        self.gridLayout_5.addWidget(self.label_21, 1, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_22.setMaximumSize(QtCore.QSize(100, 100))
        self.label_22.setText("")
        self.label_22.setPixmap(QtGui.QPixmap("C:/Users/DeadlyComputer/Desktop/photo/578211-gettyimages-542930526.jpg"))
        self.label_22.setScaledContents(True)
        self.label_22.setObjectName("label_22")
        self.gridLayout_5.addWidget(self.label_22, 1, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_23.setMaximumSize(QtCore.QSize(100, 100))
        self.label_23.setText("")
        self.label_23.setPixmap(QtGui.QPixmap("C:/Users/DeadlyComputer/Desktop/photo/578211-gettyimages-542930526.jpg"))
        self.label_23.setScaledContents(True)
        self.label_23.setObjectName("label_23")
        self.gridLayout_5.addWidget(self.label_23, 1, 2, 1, 1)
        """

    def info(self):
        self.label_225 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_225.setObjectName("label_225")
        self.gridLayout_8.addWidget(self.label_225, 4, 0, 1, 2)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.label_8.setText("TextLabel")
        self.gridLayout_8.addWidget(self.label_8, 0, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.label_11.setText("TextLabel")
        self.gridLayout_8.addWidget(self.label_11, 1, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.label_10.setText("TextLabel")
        self.gridLayout_8.addWidget(self.label_10, 0, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_13.setObjectName("label_13")
        self.label_13.setText("TextLabel")
        self.gridLayout_8.addWidget(self.label_13, 1, 1, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_25.setObjectName("label_25")
        self.label_25.setText("TextLabel")
        self.gridLayout_8.addWidget(self.label_25, 2, 0, 1, 1)
        self.label_224 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_224.setObjectName("label_224")
        self.label_224.setText("TextLabel")
        self.gridLayout_8.addWidget(self.label_224, 2, 1, 1, 1)
        self.label_224 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_224.setObjectName("label_224")
        self.label_224.setText("TextLabel")
        self.gridLayout_8.addWidget(self.label_224, 4, 0, 1, 2)
        self.commandLinkButton = QtWidgets.QCommandLinkButton(self.gridLayoutWidget)
        self.commandLinkButton.setObjectName("commandLinkButton")
        self.commandLinkButton.setText("dqwd")
        self.gridLayout_8.addWidget(self.commandLinkButton, 5, 0, 1, 2)

    def paginationForSeries(self):
        self.tabWidget = QtWidgets.QTabWidget(self.obj)
        self.tabWidget.setGeometry(QtCore.QRect(80, 430, 1571, 581))
        self.tabWidget.setObjectName("tabWidget")
        self.tabWidgetPage1 = QtWidgets.QWidget()
        self.tabWidgetPage1.setObjectName("tabWidgetPage1")
        self.grid = QtWidgets.QWidget(self.tabWidgetPage1)

    def series(self):

        #grid
        self.gridLayoutWidget = QtWidgets.QWidget(self.obj)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(560, 180, 391, 161))

        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")

    def seriesResult(self):
        self.tabWidgetPage1 = QtWidgets.QWidget()
        self.tabWidgetPage1.setObjectName("tabWidgetPage1")
        left=5
        top=0
        for item in self.seriesList:

            grid = QtWidgets.QWidget(self.tabWidgetPage1)
            grid.setGeometry(QtCore.QRect(left,top, 450, 300))
            grid.setObjectName("gridLayoutWidget_15")
            seriesItem = QtWidgets.QGridLayout(grid)
            seriesItem.setContentsMargins(0, 0, 0, 0)
            seriesItem.setObjectName("seriesItem")
            title = QtWidgets.QLabel(grid)
            title.setObjectName("seriesTitle")
            title.setText("<html><head/><body><p align=\"center\";><span style=\" font-size:18pt; font-weight:600; \">"+item['name']+"</span></p></body></html>")
            seriesItem.addWidget(title, 0, 0, 1, 0)

            self.seriesPhoto_35 = QtWidgets.QLabel(grid)
            self.seriesPhoto_35.setMaximumSize(QtCore.QSize(100, 150))
            self.seriesPhoto_35.setText("")
            self.seriesPhoto_35.setPixmap(QtGui.QPixmap(item['avatar']))
            self.seriesPhoto_35.setScaledContents(True)
            self.seriesPhoto_35.setObjectName("seriesPhoto_35")
            seriesItem.addWidget(self.seriesPhoto_35, 1, 0, 5, 1)

            row=1
            for el in item['movies']:
                name = QtWidgets.QLabel(grid)
                name.setMinimumSize(QtCore.QSize(30, 0))
                name.setMaximumSize(QtCore.QSize(10000000, 16777215))
                name.setObjectName("nameLabel")
                name.setText(el)
                seriesItem.addWidget(name, row, 1, 1, 1)

                info = QtWidgets.QPushButton(grid)
                info.setMinimumSize(QtCore.QSize(30, 0))
                info.setMaximumSize(QtCore.QSize(10, 16777215))
                info.setObjectName("InfoButton")
                info.setText("Info")
                seriesItem.addWidget(info, row, 3, 1, 1)

                play = QtWidgets.QPushButton(grid)
                play.setMinimumSize(QtCore.QSize(30, 0))
                play.setMaximumSize(QtCore.QSize(10, 16777215))
                play.setObjectName("playButton")
                play.setText("play")
                seriesItem.addWidget(play, row, 2, 1, 1)

                row=row+1

            left=left+350

            if len(item['movies']) > 4:
                self.commandLinkButton_35 = QtWidgets.QCommandLinkButton(grid)
                self.commandLinkButton_35.setObjectName("commandLinkButton_35")
                self.commandLinkButton_35.setText("show more")
                seriesItem.addWidget(self.commandLinkButton_35, 6, 0, 1, 4)


        self.tabWidget.addTab(self.tabWidgetPage1, "")

        """

        self.tabWidgetPage1 = QtWidgets.QWidget()
        self.tabWidgetPage1.setObjectName("tabWidgetPage1")
        self.gridLayoutWidget_15 = QtWidgets.QWidget(self.tabWidgetPage1)
        self.gridLayoutWidget_15.setGeometry(QtCore.QRect(10, 20, 370, 251))
        self.gridLayoutWidget_15.setObjectName("gridLayoutWidget_15")
        self.seriesItem = QtWidgets.QGridLayout(self.gridLayoutWidget_15)
        self.seriesItem.setContentsMargins(0, 0, 0, 0)
        self.seriesItem.setObjectName("seriesItem")

        self.label_214 = QtWidgets.QLabel(self.gridLayoutWidget_15)
        self.label_214.setObjectName("seriesTitle")
        self.label_214.setText("<html><head/><body><p align=\"center\">Series List</p></body></html>")
        self.seriesItem.addWidget(self.label_214, 0, 0, 1, 4)
        self.pushButton_376 = QtWidgets.QPushButton(self.gridLayoutWidget_15)

        self.pushButton_376.setObjectName("pushButton_376")
        self.pushButton_376.setText("Info ")
        self.seriesItem.addWidget(self.pushButton_376, 1, 3, 1, 1)

        self.label_215 = QtWidgets.QLabel(self.gridLayoutWidget_15)
        self.label_215.setObjectName("label_215")
        self.seriesItem.addWidget(self.label_215, 3, 1, 1, 1)

        self.buttonInfo_35 = QtWidgets.QPushButton(self.gridLayoutWidget_15)
        self.buttonInfo_35.setObjectName("buttonInfo_35")
        self.buttonInfo_35.setText("play")
        self.seriesItem.addWidget(self.buttonInfo_35, 1, 2, 1, 1)

        self.seriesPhoto_35 = QtWidgets.QLabel(self.gridLayoutWidget_15)
        self.seriesPhoto_35.setMaximumSize(QtCore.QSize(100, 100))
        self.seriesPhoto_35.setText("")
        self.seriesPhoto_35.setPixmap(QtGui.QPixmap("C:/Users/DeadlyComputer/Desktop/photo/578211-gettyimages-542930526.jpg"))
        self.seriesPhoto_35.setScaledContents(True)
        self.seriesPhoto_35.setObjectName("seriesPhoto_35")
        self.seriesItem.addWidget(self.seriesPhoto_35, 1, 0, 5, 1)

        self.item_35 = QtWidgets.QLabel(self.gridLayoutWidget_15)
        self.item_35.setObjectName("item_35")
        self.item_35.setText("qefe ")
        self.seriesItem.addWidget(self.item_35, 1, 1, 1, 1)

        self.commandLinkButton_35 = QtWidgets.QCommandLinkButton(self.gridLayoutWidget_15)
        self.commandLinkButton_35.setObjectName("commandLinkButton_35")
        self.commandLinkButton_35.setText( "show more")
        self.seriesItem.addWidget(self.commandLinkButton_35, 6, 0, 1, 4)
        self.tabWidget.addTab(self.tabWidgetPage1, "")
        """
        """"
        self.pushButton_368 = QtWidgets.QPushButton(self.gridLayoutWidget_15)
        self.pushButton_368.setObjectName("pushButton_368")
        self.seriesList_35.addWidget(self.pushButton_368, 5, 2, 1, 1)
        self.pushButton_368 = QtWidgets.QPushButton(self.gridLayoutWidget_15)
        self.pushButton_368.setObjectName("pushButton_368")
        self.seriesList_35.addWidget(self.pushButton_368, 5, 2, 1, 1)
        self.pushButton_369 = QtWidgets.QPushButton(self.gridLayoutWidget_15)
        self.pushButton_369.setObjectName("pushButton_369")
        self.seriesList_35.addWidget(self.pushButton_369, 2, 2, 1, 1)
        self.pushButton_370 = QtWidgets.QPushButton(self.gridLayoutWidget_15)
        self.pushButton_370.setObjectName("pushButton_370")
        self.seriesList_35.addWidget(self.pushButton_370, 3, 2, 1, 1)
        self.pushButton_371 = QtWidgets.QPushButton(self.gridLayoutWidget_15)
        self.pushButton_371.setObjectName("pushButton_371")
        self.seriesList_35.addWidget(self.pushButton_371, 4, 2, 1, 1)
        self.pushButton_372 = QtWidgets.QPushButton(self.gridLayoutWidget_15)
        self.pushButton_372.setObjectName("pushButton_372")
        self.seriesList_35.addWidget(self.pushButton_372, 2, 3, 1, 1)
        self.pushButton_373 = QtWidgets.QPushButton(self.gridLayoutWidget_15)
        self.pushButton_373.setObjectName("pushButton_373")
        self.seriesList_35.addWidget(self.pushButton_373, 4, 3, 1, 1)
        self.pushButton_374 = QtWidgets.QPushButton(self.gridLayoutWidget_15)
        self.pushButton_374.setObjectName("pushButton_374")
        self.seriesList_35.addWidget(self.pushButton_374, 3, 3, 1, 1)
        self.pushButton_375 = QtWidgets.QPushButton(self.gridLayoutWidget_15)
        self.pushButton_375.setObjectName("pushButton_375")
        self.seriesList_35.addWidget(self.pushButton_375, 5, 3, 1, 1)
        self.pushButton_376 = QtWidgets.QPushButton(self.gridLayoutWidget_15)
        self.pushButton_376.setObjectName("pushButton_376")
        self.seriesList_35.addWidget(self.pushButton_376, 1, 3, 1, 1)
        self.label_215 = QtWidgets.QLabel(self.gridLayoutWidget_15)
        self.label_215.setObjectName("label_215")
        self.seriesList_35.addWidget(self.label_215, 3, 1, 1, 1)
        self.buttonInfo_35 = QtWidgets.QPushButton(self.gridLayoutWidget_15)
        self.buttonInfo_35.setObjectName("buttonInfo_35")
        self.seriesList_35.addWidget(self.buttonInfo_35, 1, 2, 1, 1)
        self.seriesPhoto_35 = QtWidgets.QLabel(self.gridLayoutWidget_15)
        self.seriesPhoto_35.setMaximumSize(QtCore.QSize(100, 100))
        self.seriesPhoto_35.setText("")
        self.seriesPhoto_35.setPixmap(
            QtGui.QPixmap("C:/Users/DeadlyComputer/Desktop/photo/578211-gettyimages-542930526.jpg"))
        self.seriesPhoto_35.setScaledContents(True)
        self.seriesPhoto_35.setObjectName("seriesPhoto_35")
        self.seriesList_35.addWidget(self.seriesPhoto_35, 1, 0, 5, 1)
        self.item_35 = QtWidgets.QLabel(self.gridLayoutWidget_15)
        self.item_35.setObjectName("item_35")
        self.seriesList_35.addWidget(self.item_35, 1, 1, 1, 1)
        """

    def setupUi(self):
        self.createObj()
        """
        self.obj=QtWidgets.QMainWindow()
        self.obj.setObjectName("StarList")
        self.obj.resize(1707, 1036)
        """
        self.avatar()
        """
        self.label = QtWidgets.QLabel(self.obj)
        self.label.setGeometry(QtCore.QRect(100, 80, 341, 331))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("C:/Users/DeadlyComputer/Desktop/photo/578211-gettyimages-542930526.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        """
        self.title()
        """
        self.Title = QtWidgets.QLabel(self.obj)
        self.Title.setGeometry(QtCore.QRect(530, 60, 391, 91))
        self.Title.setObjectName("Title")
         """
        self.galery()
        """
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.obj)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(1040, 50, 581, 361))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_9.setMaximumSize(QtCore.QSize(100, 100))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("C:/Users/DeadlyComputer/Desktop/photo/578211-gettyimages-542930526.jpg"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.gridLayout_5.addWidget(self.label_9, 0, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_20.setMaximumSize(QtCore.QSize(100, 100))
        self.label_20.setText("")
        self.label_20.setPixmap(QtGui.QPixmap("C:/Users/DeadlyComputer/Desktop/photo/578211-gettyimages-542930526.jpg"))
        self.label_20.setScaledContents(True)
        self.label_20.setObjectName("label_20")
        self.gridLayout_5.addWidget(self.label_20, 0, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_12.setMaximumSize(QtCore.QSize(100, 100))
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap("C:/Users/DeadlyComputer/Desktop/photo/578211-gettyimages-542930526.jpg"))
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName("label_12")
        self.gridLayout_5.addWidget(self.label_12, 0, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_21.setMaximumSize(QtCore.QSize(100, 100))
        self.label_21.setText("")
        self.label_21.setPixmap(QtGui.QPixmap("C:/Users/DeadlyComputer/Desktop/photo/578211-gettyimages-542930526.jpg"))
        self.label_21.setScaledContents(True)
        self.label_21.setObjectName("label_21")
        self.gridLayout_5.addWidget(self.label_21, 1, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_22.setMaximumSize(QtCore.QSize(100, 100))
        self.label_22.setText("")
        self.label_22.setPixmap(QtGui.QPixmap("C:/Users/DeadlyComputer/Desktop/photo/578211-gettyimages-542930526.jpg"))
        self.label_22.setScaledContents(True)
        self.label_22.setObjectName("label_22")
        self.gridLayout_5.addWidget(self.label_22, 1, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_23.setMaximumSize(QtCore.QSize(100, 100))
        self.label_23.setText("")
        self.label_23.setPixmap(QtGui.QPixmap("C:/Users/DeadlyComputer/Desktop/photo/578211-gettyimages-542930526.jpg"))
        self.label_23.setScaledContents(True)
        self.label_23.setObjectName("label_23")
        self.gridLayout_5.addWidget(self.label_23, 1, 2, 1, 1)
        """
        self.series()
        """
        self.gridLayoutWidget = QtWidgets.QWidget(self.obj)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(560, 180, 391, 161))
        
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        """
        self.info()
        """
        self.label_225 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_225.setObjectName("label_225")
        self.gridLayout_8.addWidget(self.label_225, 4, 0, 1, 2)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout_8.addWidget(self.label_8, 0, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.gridLayout_8.addWidget(self.label_11, 1, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.gridLayout_8.addWidget(self.label_10, 0, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_13.setObjectName("label_13")
        self.gridLayout_8.addWidget(self.label_13, 1, 1, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_25.setObjectName("label_25")
        self.gridLayout_8.addWidget(self.label_25, 2, 0, 1, 1)
        self.label_224 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_224.setObjectName("label_224")
        self.gridLayout_8.addWidget(self.label_224, 2, 1, 1, 1)
        self.commandLinkButton = QtWidgets.QCommandLinkButton(self.gridLayoutWidget)
        self.commandLinkButton.setObjectName("commandLinkButton")
        self.gridLayout_8.addWidget(self.commandLinkButton, 5, 0, 1, 2)
        """
        self.paginationForSeries()

        """
        self.tabWidget = QtWidgets.QTabWidget(self.obj)
        self.tabWidget.setGeometry(QtCore.QRect(80, 430, 1571, 581))
        self.tabWidget.setObjectName("tabWidget")
        self.tabWidgetPage1 = QtWidgets.QWidget()
        self.tabWidgetPage1.setObjectName("tabWidgetPage1")
        self.gridLayoutWidget_15 = QtWidgets.QWidget(self.tabWidgetPage1)
        """

        self.seriesResult()


        """
        self.pushButton_368 = QtWidgets.QPushButton(self.gridLayoutWidget_15)
        self.pushButton_368.setObjectName("pushButton_368")
        self.seriesList_35.addWidget(self.pushButton_368, 5, 2, 1, 1)
        self.pushButton_369 = QtWidgets.QPushButton(self.gridLayoutWidget_15)
        self.pushButton_369.setObjectName("pushButton_369")
        self.seriesList_35.addWidget(self.pushButton_369, 2, 2, 1, 1)
        self.pushButton_370 = QtWidgets.QPushButton(self.gridLayoutWidget_15)
        self.pushButton_370.setObjectName("pushButton_370")
        self.seriesList_35.addWidget(self.pushButton_370, 3, 2, 1, 1)
        self.pushButton_371 = QtWidgets.QPushButton(self.gridLayoutWidget_15)
        self.pushButton_371.setObjectName("pushButton_371")
        self.seriesList_35.addWidget(self.pushButton_371, 4, 2, 1, 1)
        self.pushButton_372 = QtWidgets.QPushButton(self.gridLayoutWidget_15)
        self.pushButton_372.setObjectName("pushButton_372")
        self.seriesList_35.addWidget(self.pushButton_372, 2, 3, 1, 1)
        self.pushButton_373 = QtWidgets.QPushButton(self.gridLayoutWidget_15)
        self.pushButton_373.setObjectName("pushButton_373")
        self.seriesList_35.addWidget(self.pushButton_373, 4, 3, 1, 1)
        self.pushButton_374 = QtWidgets.QPushButton(self.gridLayoutWidget_15)
        self.pushButton_374.setObjectName("pushButton_374")
        self.seriesList_35.addWidget(self.pushButton_374, 3, 3, 1, 1)
        self.pushButton_375 = QtWidgets.QPushButton(self.gridLayoutWidget_15)
        self.pushButton_375.setObjectName("pushButton_375")
        self.seriesList_35.addWidget(self.pushButton_375, 5, 3, 1, 1)
        self.pushButton_376 = QtWidgets.QPushButton(self.gridLayoutWidget_15)
        self.pushButton_376.setObjectName("pushButton_376")
        self.seriesList_35.addWidget(self.pushButton_376, 1, 3, 1, 1)
        self.label_215 = QtWidgets.QLabel(self.gridLayoutWidget_15)
        self.label_215.setObjectName("label_215")
        self.seriesList_35.addWidget(self.label_215, 3, 1, 1, 1)
        self.buttonInfo_35 = QtWidgets.QPushButton(self.gridLayoutWidget_15)
        self.buttonInfo_35.setObjectName("buttonInfo_35")
        self.seriesList_35.addWidget(self.buttonInfo_35, 1, 2, 1, 1)
        self.seriesPhoto_35 = QtWidgets.QLabel(self.gridLayoutWidget_15)
        self.seriesPhoto_35.setMaximumSize(QtCore.QSize(100, 100))
        self.seriesPhoto_35.setText("")
        self.seriesPhoto_35.setPixmap(QtGui.QPixmap("C:/Users/DeadlyComputer/Desktop/photo/578211-gettyimages-542930526.jpg"))
        self.seriesPhoto_35.setScaledContents(True)
        self.seriesPhoto_35.setObjectName("seriesPhoto_35")
        self.seriesList_35.addWidget(self.seriesPhoto_35, 1, 0, 5, 1)
        self.item_35 = QtWidgets.QLabel(self.gridLayoutWidget_15)
        self.item_35.setObjectName("item_35")
        self.seriesList_35.addWidget(self.item_35, 1, 1, 1, 1)
        """
        
        self.tabWidget.addTab(self.tabWidgetPage1, "")

        """
        self.label_216 = QtWidgets.QLabel(self.gridLayoutWidget_15)
        self.label_216.setObjectName("label_216")
        self.seriesList_35.addWidget(self.label_216, 2, 1, 1, 1)
        self.label_217 = QtWidgets.QLabel(self.gridLayoutWidget_15)
        self.label_217.setObjectName("label_217")
        self.seriesList_35.addWidget(self.label_217, 5, 1, 1, 1)
        self.label_218 = QtWidgets.QLabel(self.gridLayoutWidget_15)
        self.label_218.setObjectName("label_218")
        self.seriesList_35.addWidget(self.label_218, 4, 1, 1, 1)
        self.commandLinkButton_35 = QtWidgets.QCommandLinkButton(self.gridLayoutWidget_15)
        self.commandLinkButton_35.setObjectName("commandLinkButton_35")
        self.seriesList_35.addWidget(self.commandLinkButton_35, 6, 0, 1, 4)
        self.gridLayoutWidget_16 = QtWidgets.QWidget(self.tabWidgetPage1)
        self.gridLayoutWidget_16.setGeometry(QtCore.QRect(400, 20, 370, 251))
        self.gridLayoutWidget_16.setObjectName("gridLayoutWidget_16")
        self.seriesList_36 = QtWidgets.QGridLayout(self.gridLayoutWidget_16)
        self.seriesList_36.setContentsMargins(0, 0, 0, 0)
        self.seriesList_36.setObjectName("seriesList_36")
        self.label_219 = QtWidgets.QLabel(self.gridLayoutWidget_16)
        self.label_219.setObjectName("label_219")
        self.seriesList_36.addWidget(self.label_219, 0, 0, 1, 4)
        self.pushButton_377 = QtWidgets.QPushButton(self.gridLayoutWidget_16)
        self.pushButton_377.setObjectName("pushButton_377")
        self.seriesList_36.addWidget(self.pushButton_377, 5, 2, 1, 1)
        self.pushButton_378 = QtWidgets.QPushButton(self.gridLayoutWidget_16)
        self.pushButton_378.setObjectName("pushButton_378")
        self.seriesList_36.addWidget(self.pushButton_378, 2, 2, 1, 1)
        self.pushButton_379 = QtWidgets.QPushButton(self.gridLayoutWidget_16)
        self.pushButton_379.setObjectName("pushButton_379")
        self.seriesList_36.addWidget(self.pushButton_379, 3, 2, 1, 1)
        self.pushButton_380 = QtWidgets.QPushButton(self.gridLayoutWidget_16)
        self.pushButton_380.setObjectName("pushButton_380")
        self.seriesList_36.addWidget(self.pushButton_380, 4, 2, 1, 1)
        self.pushButton_381 = QtWidgets.QPushButton(self.gridLayoutWidget_16)
        self.pushButton_381.setObjectName("pushButton_381")
        self.seriesList_36.addWidget(self.pushButton_381, 2, 3, 1, 1)
        self.pushButton_382 = QtWidgets.QPushButton(self.gridLayoutWidget_16)
        self.pushButton_382.setObjectName("pushButton_382")
        self.seriesList_36.addWidget(self.pushButton_382, 4, 3, 1, 1)
        self.pushButton_383 = QtWidgets.QPushButton(self.gridLayoutWidget_16)
        self.pushButton_383.setObjectName("pushButton_383")
        self.seriesList_36.addWidget(self.pushButton_383, 3, 3, 1, 1)
        self.pushButton_384 = QtWidgets.QPushButton(self.gridLayoutWidget_16)
        self.pushButton_384.setObjectName("pushButton_384")
        self.seriesList_36.addWidget(self.pushButton_384, 5, 3, 1, 1)
        self.pushButton_385 = QtWidgets.QPushButton(self.gridLayoutWidget_16)
        self.pushButton_385.setObjectName("pushButton_385")
        self.seriesList_36.addWidget(self.pushButton_385, 1, 3, 1, 1)
        self.label_220 = QtWidgets.QLabel(self.gridLayoutWidget_16)
        self.label_220.setObjectName("label_220")
        self.seriesList_36.addWidget(self.label_220, 3, 1, 1, 1)
        self.buttonInfo_36 = QtWidgets.QPushButton(self.gridLayoutWidget_16)
        self.buttonInfo_36.setObjectName("buttonInfo_36")
        self.seriesList_36.addWidget(self.buttonInfo_36, 1, 2, 1, 1)
        self.seriesPhoto_36 = QtWidgets.QLabel(self.gridLayoutWidget_16)
        self.seriesPhoto_36.setMaximumSize(QtCore.QSize(100, 100))
        self.seriesPhoto_36.setText("")
        self.seriesPhoto_36.setPixmap(QtGui.QPixmap("C:/Users/DeadlyComputer/Desktop/photo/578211-gettyimages-542930526.jpg"))
        self.seriesPhoto_36.setScaledContents(True)
        self.seriesPhoto_36.setObjectName("seriesPhoto_36")
        self.seriesList_36.addWidget(self.seriesPhoto_36, 1, 0, 5, 1)
        self.item_36 = QtWidgets.QLabel(self.gridLayoutWidget_16)
        self.item_36.setObjectName("item_36")
        self.seriesList_36.addWidget(self.item_36, 1, 1, 1, 1)
        self.label_221 = QtWidgets.QLabel(self.gridLayoutWidget_16)
        self.label_221.setObjectName("label_221")
        self.seriesList_36.addWidget(self.label_221, 2, 1, 1, 1)
        self.label_222 = QtWidgets.QLabel(self.gridLayoutWidget_16)
        self.label_222.setObjectName("label_222")
        self.seriesList_36.addWidget(self.label_222, 5, 1, 1, 1)
        self.label_223 = QtWidgets.QLabel(self.gridLayoutWidget_16)
        self.label_223.setObjectName("label_223")
        self.seriesList_36.addWidget(self.label_223, 4, 1, 1, 1)
        self.commandLinkButton_36 = QtWidgets.QCommandLinkButton(self.gridLayoutWidget_16)
        self.commandLinkButton_36.setObjectName("commandLinkButton_36")
        self.seriesList_36.addWidget(self.commandLinkButton_36, 6, 0, 1, 4)
        self.gridLayoutWidget_17 = QtWidgets.QWidget(self.tabWidgetPage1)
        self.gridLayoutWidget_17.setGeometry(QtCore.QRect(790, 20, 370, 251))
        self.gridLayoutWidget_17.setObjectName("gridLayoutWidget_17")
        self.seriesList_37 = QtWidgets.QGridLayout(self.gridLayoutWidget_17)
        self.seriesList_37.setContentsMargins(0, 0, 0, 0)
        self.seriesList_37.setObjectName("seriesList_37")
        self.label_226 = QtWidgets.QLabel(self.gridLayoutWidget_17)
        self.label_226.setObjectName("label_226")
        self.seriesList_37.addWidget(self.label_226, 0, 0, 1, 4)
        self.pushButton_386 = QtWidgets.QPushButton(self.gridLayoutWidget_17)
        self.pushButton_386.setObjectName("pushButton_386")
        self.seriesList_37.addWidget(self.pushButton_386, 5, 2, 1, 1)
        self.pushButton_387 = QtWidgets.QPushButton(self.gridLayoutWidget_17)
        self.pushButton_387.setObjectName("pushButton_387")
        self.seriesList_37.addWidget(self.pushButton_387, 2, 2, 1, 1)
        self.pushButton_388 = QtWidgets.QPushButton(self.gridLayoutWidget_17)
        self.pushButton_388.setObjectName("pushButton_388")
        self.seriesList_37.addWidget(self.pushButton_388, 3, 2, 1, 1)
        self.pushButton_389 = QtWidgets.QPushButton(self.gridLayoutWidget_17)
        self.pushButton_389.setObjectName("pushButton_389")
        self.seriesList_37.addWidget(self.pushButton_389, 4, 2, 1, 1)
        self.pushButton_390 = QtWidgets.QPushButton(self.gridLayoutWidget_17)
        self.pushButton_390.setObjectName("pushButton_390")
        self.seriesList_37.addWidget(self.pushButton_390, 2, 3, 1, 1)
        self.pushButton_391 = QtWidgets.QPushButton(self.gridLayoutWidget_17)
        self.pushButton_391.setObjectName("pushButton_391")
        self.seriesList_37.addWidget(self.pushButton_391, 4, 3, 1, 1)
        self.pushButton_392 = QtWidgets.QPushButton(self.gridLayoutWidget_17)
        self.pushButton_392.setObjectName("pushButton_392")
        self.seriesList_37.addWidget(self.pushButton_392, 3, 3, 1, 1)
        self.pushButton_393 = QtWidgets.QPushButton(self.gridLayoutWidget_17)
        self.pushButton_393.setObjectName("pushButton_393")
        self.seriesList_37.addWidget(self.pushButton_393, 5, 3, 1, 1)
        self.pushButton_394 = QtWidgets.QPushButton(self.gridLayoutWidget_17)
        self.pushButton_394.setObjectName("pushButton_394")
        self.seriesList_37.addWidget(self.pushButton_394, 1, 3, 1, 1)
        self.label_227 = QtWidgets.QLabel(self.gridLayoutWidget_17)
        self.label_227.setObjectName("label_227")
        self.seriesList_37.addWidget(self.label_227, 3, 1, 1, 1)
        self.buttonInfo_37 = QtWidgets.QPushButton(self.gridLayoutWidget_17)
        self.buttonInfo_37.setObjectName("buttonInfo_37")
        self.seriesList_37.addWidget(self.buttonInfo_37, 1, 2, 1, 1)
        self.seriesPhoto_37 = QtWidgets.QLabel(self.gridLayoutWidget_17)
        self.seriesPhoto_37.setMaximumSize(QtCore.QSize(100, 100))
        self.seriesPhoto_37.setText("")
        self.seriesPhoto_37.setPixmap(QtGui.QPixmap("C:/Users/DeadlyComputer/Desktop/photo/578211-gettyimages-542930526.jpg"))
        self.seriesPhoto_37.setScaledContents(True)
        self.seriesPhoto_37.setObjectName("seriesPhoto_37")
        self.seriesList_37.addWidget(self.seriesPhoto_37, 1, 0, 5, 1)
        self.item_37 = QtWidgets.QLabel(self.gridLayoutWidget_17)
        self.item_37.setObjectName("item_37")
        self.seriesList_37.addWidget(self.item_37, 1, 1, 1, 1)
        self.label_228 = QtWidgets.QLabel(self.gridLayoutWidget_17)
        self.label_228.setObjectName("label_228")
        self.seriesList_37.addWidget(self.label_228, 2, 1, 1, 1)
        self.label_229 = QtWidgets.QLabel(self.gridLayoutWidget_17)
        self.label_229.setObjectName("label_229")
        self.seriesList_37.addWidget(self.label_229, 5, 1, 1, 1)
        self.label_230 = QtWidgets.QLabel(self.gridLayoutWidget_17)
        self.label_230.setObjectName("label_230")
        self.seriesList_37.addWidget(self.label_230, 4, 1, 1, 1)
        self.commandLinkButton_37 = QtWidgets.QCommandLinkButton(self.gridLayoutWidget_17)
        self.commandLinkButton_37.setObjectName("commandLinkButton_37")
        self.seriesList_37.addWidget(self.commandLinkButton_37, 6, 0, 1, 4)
        self.gridLayoutWidget_18 = QtWidgets.QWidget(self.tabWidgetPage1)
        self.gridLayoutWidget_18.setGeometry(QtCore.QRect(1180, 20, 370, 251))
        self.gridLayoutWidget_18.setObjectName("gridLayoutWidget_18")
        self.seriesList_38 = QtWidgets.QGridLayout(self.gridLayoutWidget_18)
        self.seriesList_38.setContentsMargins(0, 0, 0, 0)
        self.seriesList_38.setObjectName("seriesList_38")
        self.label_231 = QtWidgets.QLabel(self.gridLayoutWidget_18)
        self.label_231.setObjectName("label_231")
        self.seriesList_38.addWidget(self.label_231, 0, 0, 1, 4)
        self.pushButton_395 = QtWidgets.QPushButton(self.gridLayoutWidget_18)
        self.pushButton_395.setObjectName("pushButton_395")
        self.seriesList_38.addWidget(self.pushButton_395, 5, 2, 1, 1)
        self.pushButton_396 = QtWidgets.QPushButton(self.gridLayoutWidget_18)
        self.pushButton_396.setObjectName("pushButton_396")
        self.seriesList_38.addWidget(self.pushButton_396, 2, 2, 1, 1)
        self.pushButton_397 = QtWidgets.QPushButton(self.gridLayoutWidget_18)
        self.pushButton_397.setObjectName("pushButton_397")
        self.seriesList_38.addWidget(self.pushButton_397, 3, 2, 1, 1)
        self.pushButton_398 = QtWidgets.QPushButton(self.gridLayoutWidget_18)
        self.pushButton_398.setObjectName("pushButton_398")
        self.seriesList_38.addWidget(self.pushButton_398, 4, 2, 1, 1)
        self.pushButton_399 = QtWidgets.QPushButton(self.gridLayoutWidget_18)
        self.pushButton_399.setObjectName("pushButton_399")
        self.seriesList_38.addWidget(self.pushButton_399, 2, 3, 1, 1)
        self.pushButton_400 = QtWidgets.QPushButton(self.gridLayoutWidget_18)
        self.pushButton_400.setObjectName("pushButton_400")
        self.seriesList_38.addWidget(self.pushButton_400, 4, 3, 1, 1)
        self.pushButton_401 = QtWidgets.QPushButton(self.gridLayoutWidget_18)
        self.pushButton_401.setObjectName("pushButton_401")
        self.seriesList_38.addWidget(self.pushButton_401, 3, 3, 1, 1)
        self.pushButton_402 = QtWidgets.QPushButton(self.gridLayoutWidget_18)
        self.pushButton_402.setObjectName("pushButton_402")
        self.seriesList_38.addWidget(self.pushButton_402, 5, 3, 1, 1)
        self.pushButton_403 = QtWidgets.QPushButton(self.gridLayoutWidget_18)
        self.pushButton_403.setObjectName("pushButton_403")
        self.seriesList_38.addWidget(self.pushButton_403, 1, 3, 1, 1)
        self.label_232 = QtWidgets.QLabel(self.gridLayoutWidget_18)
        self.label_232.setObjectName("label_232")
        self.seriesList_38.addWidget(self.label_232, 3, 1, 1, 1)
        self.buttonInfo_38 = QtWidgets.QPushButton(self.gridLayoutWidget_18)
        self.buttonInfo_38.setObjectName("buttonInfo_38")
        self.seriesList_38.addWidget(self.buttonInfo_38, 1, 2, 1, 1)
        self.seriesPhoto_38 = QtWidgets.QLabel(self.gridLayoutWidget_18)
        self.seriesPhoto_38.setMaximumSize(QtCore.QSize(100, 100))
        self.seriesPhoto_38.setText("")
        self.seriesPhoto_38.setPixmap(QtGui.QPixmap("C:/Users/DeadlyComputer/Desktop/photo/578211-gettyimages-542930526.jpg"))
        self.seriesPhoto_38.setScaledContents(True)
        self.seriesPhoto_38.setObjectName("seriesPhoto_38")
        self.seriesList_38.addWidget(self.seriesPhoto_38, 1, 0, 5, 1)
        self.item_38 = QtWidgets.QLabel(self.gridLayoutWidget_18)
        self.item_38.setObjectName("item_38")
        self.seriesList_38.addWidget(self.item_38, 1, 1, 1, 1)
        self.label_233 = QtWidgets.QLabel(self.gridLayoutWidget_18)
        self.label_233.setObjectName("label_233")
        self.seriesList_38.addWidget(self.label_233, 2, 1, 1, 1)
        self.label_234 = QtWidgets.QLabel(self.gridLayoutWidget_18)
        self.label_234.setObjectName("label_234")
        self.seriesList_38.addWidget(self.label_234, 5, 1, 1, 1)
        self.label_235 = QtWidgets.QLabel(self.gridLayoutWidget_18)
        self.label_235.setObjectName("label_235")
        self.seriesList_38.addWidget(self.label_235, 4, 1, 1, 1)
        self.commandLinkButton_38 = QtWidgets.QCommandLinkButton(self.gridLayoutWidget_18)
        self.commandLinkButton_38.setObjectName("commandLinkButton_38")
        self.seriesList_38.addWidget(self.commandLinkButton_38, 6, 0, 1, 4)
        self.gridLayoutWidget_19 = QtWidgets.QWidget(self.tabWidgetPage1)
        self.gridLayoutWidget_19.setGeometry(QtCore.QRect(10, 290, 370, 251))
        self.gridLayoutWidget_19.setObjectName("gridLayoutWidget_19")
        self.seriesList_39 = QtWidgets.QGridLayout(self.gridLayoutWidget_19)
        self.seriesList_39.setContentsMargins(0, 0, 0, 0)
        self.seriesList_39.setObjectName("seriesList_39")
        self.label_236 = QtWidgets.QLabel(self.gridLayoutWidget_19)
        self.label_236.setObjectName("label_236")
        self.seriesList_39.addWidget(self.label_236, 0, 0, 1, 4)
        self.pushButton_404 = QtWidgets.QPushButton(self.gridLayoutWidget_19)
        self.pushButton_404.setObjectName("pushButton_404")
        self.seriesList_39.addWidget(self.pushButton_404, 5, 2, 1, 1)
        self.pushButton_405 = QtWidgets.QPushButton(self.gridLayoutWidget_19)
        self.pushButton_405.setObjectName("pushButton_405")
        self.seriesList_39.addWidget(self.pushButton_405, 2, 2, 1, 1)
        self.pushButton_406 = QtWidgets.QPushButton(self.gridLayoutWidget_19)
        self.pushButton_406.setObjectName("pushButton_406")
        self.seriesList_39.addWidget(self.pushButton_406, 3, 2, 1, 1)
        self.pushButton_407 = QtWidgets.QPushButton(self.gridLayoutWidget_19)
        self.pushButton_407.setObjectName("pushButton_407")
        self.seriesList_39.addWidget(self.pushButton_407, 4, 2, 1, 1)
        self.pushButton_408 = QtWidgets.QPushButton(self.gridLayoutWidget_19)
        self.pushButton_408.setObjectName("pushButton_408")
        self.seriesList_39.addWidget(self.pushButton_408, 2, 3, 1, 1)
        self.pushButton_409 = QtWidgets.QPushButton(self.gridLayoutWidget_19)
        self.pushButton_409.setObjectName("pushButton_409")
        self.seriesList_39.addWidget(self.pushButton_409, 4, 3, 1, 1)
        self.pushButton_410 = QtWidgets.QPushButton(self.gridLayoutWidget_19)
        self.pushButton_410.setObjectName("pushButton_410")
        self.seriesList_39.addWidget(self.pushButton_410, 3, 3, 1, 1)
        self.pushButton_411 = QtWidgets.QPushButton(self.gridLayoutWidget_19)
        self.pushButton_411.setObjectName("pushButton_411")
        self.seriesList_39.addWidget(self.pushButton_411, 5, 3, 1, 1)
        self.pushButton_412 = QtWidgets.QPushButton(self.gridLayoutWidget_19)
        self.pushButton_412.setObjectName("pushButton_412")
        self.seriesList_39.addWidget(self.pushButton_412, 1, 3, 1, 1)
        self.label_237 = QtWidgets.QLabel(self.gridLayoutWidget_19)
        self.label_237.setObjectName("label_237")
        self.seriesList_39.addWidget(self.label_237, 3, 1, 1, 1)
        self.buttonInfo_39 = QtWidgets.QPushButton(self.gridLayoutWidget_19)
        self.buttonInfo_39.setObjectName("buttonInfo_39")
        self.seriesList_39.addWidget(self.buttonInfo_39, 1, 2, 1, 1)
        self.seriesPhoto_39 = QtWidgets.QLabel(self.gridLayoutWidget_19)
        self.seriesPhoto_39.setMaximumSize(QtCore.QSize(100, 100))
        self.seriesPhoto_39.setText("")
        self.seriesPhoto_39.setPixmap(QtGui.QPixmap("C:/Users/DeadlyComputer/Desktop/photo/578211-gettyimages-542930526.jpg"))
        self.seriesPhoto_39.setScaledContents(True)
        self.seriesPhoto_39.setObjectName("seriesPhoto_39")
        self.seriesList_39.addWidget(self.seriesPhoto_39, 1, 0, 5, 1)
        self.item_39 = QtWidgets.QLabel(self.gridLayoutWidget_19)
        self.item_39.setObjectName("item_39")
        self.seriesList_39.addWidget(self.item_39, 1, 1, 1, 1)
        self.label_238 = QtWidgets.QLabel(self.gridLayoutWidget_19)
        self.label_238.setObjectName("label_238")
        self.seriesList_39.addWidget(self.label_238, 2, 1, 1, 1)
        self.label_239 = QtWidgets.QLabel(self.gridLayoutWidget_19)
        self.label_239.setObjectName("label_239")
        self.seriesList_39.addWidget(self.label_239, 5, 1, 1, 1)
        self.label_240 = QtWidgets.QLabel(self.gridLayoutWidget_19)
        self.label_240.setObjectName("label_240")
        self.seriesList_39.addWidget(self.label_240, 4, 1, 1, 1)
        self.commandLinkButton_39 = QtWidgets.QCommandLinkButton(self.gridLayoutWidget_19)
        self.commandLinkButton_39.setObjectName("commandLinkButton_39")
        self.seriesList_39.addWidget(self.commandLinkButton_39, 6, 0, 1, 4)
        self.gridLayoutWidget_20 = QtWidgets.QWidget(self.tabWidgetPage1)
        self.gridLayoutWidget_20.setGeometry(QtCore.QRect(400, 290, 370, 251))
        self.gridLayoutWidget_20.setObjectName("gridLayoutWidget_20")
        self.seriesList_40 = QtWidgets.QGridLayout(self.gridLayoutWidget_20)
        self.seriesList_40.setContentsMargins(0, 0, 0, 0)
        self.seriesList_40.setObjectName("seriesList_40")
        self.label_241 = QtWidgets.QLabel(self.gridLayoutWidget_20)
        self.label_241.setObjectName("label_241")
        self.seriesList_40.addWidget(self.label_241, 0, 0, 1, 4)
        self.pushButton_413 = QtWidgets.QPushButton(self.gridLayoutWidget_20)
        self.pushButton_413.setObjectName("pushButton_413")
        self.seriesList_40.addWidget(self.pushButton_413, 5, 2, 1, 1)
        self.pushButton_414 = QtWidgets.QPushButton(self.gridLayoutWidget_20)
        self.pushButton_414.setObjectName("pushButton_414")
        self.seriesList_40.addWidget(self.pushButton_414, 2, 2, 1, 1)
        self.pushButton_415 = QtWidgets.QPushButton(self.gridLayoutWidget_20)
        self.pushButton_415.setObjectName("pushButton_415")
        self.seriesList_40.addWidget(self.pushButton_415, 3, 2, 1, 1)
        self.pushButton_416 = QtWidgets.QPushButton(self.gridLayoutWidget_20)
        self.pushButton_416.setObjectName("pushButton_416")
        self.seriesList_40.addWidget(self.pushButton_416, 4, 2, 1, 1)
        self.pushButton_417 = QtWidgets.QPushButton(self.gridLayoutWidget_20)
        self.pushButton_417.setObjectName("pushButton_417")
        self.seriesList_40.addWidget(self.pushButton_417, 2, 3, 1, 1)
        self.pushButton_418 = QtWidgets.QPushButton(self.gridLayoutWidget_20)
        self.pushButton_418.setObjectName("pushButton_418")
        self.seriesList_40.addWidget(self.pushButton_418, 4, 3, 1, 1)
        self.pushButton_419 = QtWidgets.QPushButton(self.gridLayoutWidget_20)
        self.pushButton_419.setObjectName("pushButton_419")
        self.seriesList_40.addWidget(self.pushButton_419, 3, 3, 1, 1)
        self.pushButton_420 = QtWidgets.QPushButton(self.gridLayoutWidget_20)
        self.pushButton_420.setObjectName("pushButton_420")
        self.seriesList_40.addWidget(self.pushButton_420, 5, 3, 1, 1)
        self.pushButton_421 = QtWidgets.QPushButton(self.gridLayoutWidget_20)
        self.pushButton_421.setObjectName("pushButton_421")
        self.seriesList_40.addWidget(self.pushButton_421, 1, 3, 1, 1)
        self.label_242 = QtWidgets.QLabel(self.gridLayoutWidget_20)
        self.label_242.setObjectName("label_242")
        self.seriesList_40.addWidget(self.label_242, 3, 1, 1, 1)
        self.buttonInfo_40 = QtWidgets.QPushButton(self.gridLayoutWidget_20)
        self.buttonInfo_40.setObjectName("buttonInfo_40")
        self.seriesList_40.addWidget(self.buttonInfo_40, 1, 2, 1, 1)
        self.seriesPhoto_40 = QtWidgets.QLabel(self.gridLayoutWidget_20)
        self.seriesPhoto_40.setMaximumSize(QtCore.QSize(100, 100))
        self.seriesPhoto_40.setText("")
        self.seriesPhoto_40.setPixmap(QtGui.QPixmap("C:/Users/DeadlyComputer/Desktop/photo/578211-gettyimages-542930526.jpg"))
        self.seriesPhoto_40.setScaledContents(True)
        self.seriesPhoto_40.setObjectName("seriesPhoto_40")
        self.seriesList_40.addWidget(self.seriesPhoto_40, 1, 0, 5, 1)
        self.item_40 = QtWidgets.QLabel(self.gridLayoutWidget_20)
        self.item_40.setObjectName("item_40")
        self.seriesList_40.addWidget(self.item_40, 1, 1, 1, 1)
        self.label_243 = QtWidgets.QLabel(self.gridLayoutWidget_20)
        self.label_243.setObjectName("label_243")
        self.seriesList_40.addWidget(self.label_243, 2, 1, 1, 1)
        self.label_244 = QtWidgets.QLabel(self.gridLayoutWidget_20)
        self.label_244.setObjectName("label_244")
        self.seriesList_40.addWidget(self.label_244, 5, 1, 1, 1)
        self.label_245 = QtWidgets.QLabel(self.gridLayoutWidget_20)
        self.label_245.setObjectName("label_245")
        self.seriesList_40.addWidget(self.label_245, 4, 1, 1, 1)
        self.commandLinkButton_40 = QtWidgets.QCommandLinkButton(self.gridLayoutWidget_20)
        self.commandLinkButton_40.setObjectName("commandLinkButton_40")
        self.seriesList_40.addWidget(self.commandLinkButton_40, 6, 0, 1, 4)
        self.gridLayoutWidget_21 = QtWidgets.QWidget(self.tabWidgetPage1)
        self.gridLayoutWidget_21.setGeometry(QtCore.QRect(790, 290, 370, 251))
        self.gridLayoutWidget_21.setObjectName("gridLayoutWidget_21")
        self.seriesList_41 = QtWidgets.QGridLayout(self.gridLayoutWidget_21)
        self.seriesList_41.setContentsMargins(0, 0, 0, 0)
        self.seriesList_41.setObjectName("seriesList_41")
        self.label_246 = QtWidgets.QLabel(self.gridLayoutWidget_21)
        self.label_246.setObjectName("label_246")
        self.seriesList_41.addWidget(self.label_246, 0, 0, 1, 4)
        self.pushButton_422 = QtWidgets.QPushButton(self.gridLayoutWidget_21)
        self.pushButton_422.setObjectName("pushButton_422")
        self.seriesList_41.addWidget(self.pushButton_422, 5, 2, 1, 1)
        self.pushButton_423 = QtWidgets.QPushButton(self.gridLayoutWidget_21)
        self.pushButton_423.setObjectName("pushButton_423")
        self.seriesList_41.addWidget(self.pushButton_423, 2, 2, 1, 1)
        self.pushButton_424 = QtWidgets.QPushButton(self.gridLayoutWidget_21)
        self.pushButton_424.setObjectName("pushButton_424")
        self.seriesList_41.addWidget(self.pushButton_424, 3, 2, 1, 1)
        self.pushButton_425 = QtWidgets.QPushButton(self.gridLayoutWidget_21)
        self.pushButton_425.setObjectName("pushButton_425")
        self.seriesList_41.addWidget(self.pushButton_425, 4, 2, 1, 1)
        self.pushButton_426 = QtWidgets.QPushButton(self.gridLayoutWidget_21)
        self.pushButton_426.setObjectName("pushButton_426")
        self.seriesList_41.addWidget(self.pushButton_426, 2, 3, 1, 1)
        self.pushButton_427 = QtWidgets.QPushButton(self.gridLayoutWidget_21)
        self.pushButton_427.setObjectName("pushButton_427")
        self.seriesList_41.addWidget(self.pushButton_427, 4, 3, 1, 1)
        self.pushButton_428 = QtWidgets.QPushButton(self.gridLayoutWidget_21)
        self.pushButton_428.setObjectName("pushButton_428")
        self.seriesList_41.addWidget(self.pushButton_428, 3, 3, 1, 1)
        self.pushButton_429 = QtWidgets.QPushButton(self.gridLayoutWidget_21)
        self.pushButton_429.setObjectName("pushButton_429")
        self.seriesList_41.addWidget(self.pushButton_429, 5, 3, 1, 1)
        self.pushButton_430 = QtWidgets.QPushButton(self.gridLayoutWidget_21)
        self.pushButton_430.setObjectName("pushButton_430")
        self.seriesList_41.addWidget(self.pushButton_430, 1, 3, 1, 1)
        self.label_247 = QtWidgets.QLabel(self.gridLayoutWidget_21)
        self.label_247.setObjectName("label_247")
        self.seriesList_41.addWidget(self.label_247, 3, 1, 1, 1)
        self.buttonInfo_41 = QtWidgets.QPushButton(self.gridLayoutWidget_21)
        self.buttonInfo_41.setObjectName("buttonInfo_41")
        self.seriesList_41.addWidget(self.buttonInfo_41, 1, 2, 1, 1)
        self.seriesPhoto_41 = QtWidgets.QLabel(self.gridLayoutWidget_21)
        self.seriesPhoto_41.setMaximumSize(QtCore.QSize(100, 100))
        self.seriesPhoto_41.setText("")
        self.seriesPhoto_41.setPixmap(QtGui.QPixmap("C:/Users/DeadlyComputer/Desktop/photo/578211-gettyimages-542930526.jpg"))
        self.seriesPhoto_41.setScaledContents(True)
        self.seriesPhoto_41.setObjectName("seriesPhoto_41")
        self.seriesList_41.addWidget(self.seriesPhoto_41, 1, 0, 5, 1)
        self.item_41 = QtWidgets.QLabel(self.gridLayoutWidget_21)
        self.item_41.setObjectName("item_41")
        self.seriesList_41.addWidget(self.item_41, 1, 1, 1, 1)
        self.label_248 = QtWidgets.QLabel(self.gridLayoutWidget_21)
        self.label_248.setObjectName("label_248")
        self.seriesList_41.addWidget(self.label_248, 2, 1, 1, 1)
        self.label_249 = QtWidgets.QLabel(self.gridLayoutWidget_21)
        self.label_249.setObjectName("label_249")
        self.seriesList_41.addWidget(self.label_249, 5, 1, 1, 1)
        self.label_250 = QtWidgets.QLabel(self.gridLayoutWidget_21)
        self.label_250.setObjectName("label_250")
        self.seriesList_41.addWidget(self.label_250, 4, 1, 1, 1)
        self.commandLinkButton_41 = QtWidgets.QCommandLinkButton(self.gridLayoutWidget_21)
        self.commandLinkButton_41.setObjectName("commandLinkButton_41")
        self.seriesList_41.addWidget(self.commandLinkButton_41, 6, 0, 1, 4)
        self.gridLayoutWidget_22 = QtWidgets.QWidget(self.tabWidgetPage1)
        self.gridLayoutWidget_22.setGeometry(QtCore.QRect(1180, 290, 370, 251))
        self.gridLayoutWidget_22.setObjectName("gridLayoutWidget_22")
        self.seriesList_42 = QtWidgets.QGridLayout(self.gridLayoutWidget_22)
        self.seriesList_42.setContentsMargins(0, 0, 0, 0)
        self.seriesList_42.setObjectName("seriesList_42")
        self.label_251 = QtWidgets.QLabel(self.gridLayoutWidget_22)
        self.label_251.setObjectName("label_251")
        self.seriesList_42.addWidget(self.label_251, 0, 0, 1, 4)
        self.pushButton_431 = QtWidgets.QPushButton(self.gridLayoutWidget_22)
        self.pushButton_431.setObjectName("pushButton_431")
        self.seriesList_42.addWidget(self.pushButton_431, 5, 2, 1, 1)
        self.pushButton_432 = QtWidgets.QPushButton(self.gridLayoutWidget_22)
        self.pushButton_432.setObjectName("pushButton_432")
        self.seriesList_42.addWidget(self.pushButton_432, 2, 2, 1, 1)
        self.pushButton_433 = QtWidgets.QPushButton(self.gridLayoutWidget_22)
        self.pushButton_433.setObjectName("pushButton_433")
        self.seriesList_42.addWidget(self.pushButton_433, 3, 2, 1, 1)
        self.pushButton_434 = QtWidgets.QPushButton(self.gridLayoutWidget_22)
        self.pushButton_434.setObjectName("pushButton_434")
        self.seriesList_42.addWidget(self.pushButton_434, 4, 2, 1, 1)
        self.pushButton_435 = QtWidgets.QPushButton(self.gridLayoutWidget_22)
        self.pushButton_435.setObjectName("pushButton_435")
        self.seriesList_42.addWidget(self.pushButton_435, 2, 3, 1, 1)
        self.pushButton_436 = QtWidgets.QPushButton(self.gridLayoutWidget_22)
        self.pushButton_436.setObjectName("pushButton_436")
        self.seriesList_42.addWidget(self.pushButton_436, 4, 3, 1, 1)
        self.pushButton_437 = QtWidgets.QPushButton(self.gridLayoutWidget_22)
        self.pushButton_437.setObjectName("pushButton_437")
        self.seriesList_42.addWidget(self.pushButton_437, 3, 3, 1, 1)
        self.pushButton_438 = QtWidgets.QPushButton(self.gridLayoutWidget_22)
        self.pushButton_438.setObjectName("pushButton_438")
        self.seriesList_42.addWidget(self.pushButton_438, 5, 3, 1, 1)
        self.pushButton_439 = QtWidgets.QPushButton(self.gridLayoutWidget_22)
        self.pushButton_439.setObjectName("pushButton_439")
        self.seriesList_42.addWidget(self.pushButton_439, 1, 3, 1, 1)
        self.label_252 = QtWidgets.QLabel(self.gridLayoutWidget_22)
        self.label_252.setObjectName("label_252")
        self.seriesList_42.addWidget(self.label_252, 3, 1, 1, 1)
        self.buttonInfo_42 = QtWidgets.QPushButton(self.gridLayoutWidget_22)
        self.buttonInfo_42.setObjectName("buttonInfo_42")
        self.seriesList_42.addWidget(self.buttonInfo_42, 1, 2, 1, 1)
        self.seriesPhoto_42 = QtWidgets.QLabel(self.gridLayoutWidget_22)
        self.seriesPhoto_42.setMaximumSize(QtCore.QSize(100, 100))
        self.seriesPhoto_42.setText("")
        self.seriesPhoto_42.setPixmap(QtGui.QPixmap("C:/Users/DeadlyComputer/Desktop/photo/578211-gettyimages-542930526.jpg"))
        self.seriesPhoto_42.setScaledContents(True)
        self.seriesPhoto_42.setObjectName("seriesPhoto_42")
        self.seriesList_42.addWidget(self.seriesPhoto_42, 1, 0, 5, 1)
        self.item_42 = QtWidgets.QLabel(self.gridLayoutWidget_22)
        self.item_42.setObjectName("item_42")
        self.seriesList_42.addWidget(self.item_42, 1, 1, 1, 1)
        self.label_253 = QtWidgets.QLabel(self.gridLayoutWidget_22)
        self.label_253.setObjectName("label_253")
        self.seriesList_42.addWidget(self.label_253, 2, 1, 1, 1)
        self.label_254 = QtWidgets.QLabel(self.gridLayoutWidget_22)
        self.label_254.setObjectName("label_254")
        self.seriesList_42.addWidget(self.label_254, 5, 1, 1, 1)
        self.label_255 = QtWidgets.QLabel(self.gridLayoutWidget_22)
        self.label_255.setObjectName("label_255")
        self.seriesList_42.addWidget(self.label_255, 4, 1, 1, 1)
        self.commandLinkButton_42 = QtWidgets.QCommandLinkButton(self.gridLayoutWidget_22)
        self.commandLinkButton_42.setObjectName("commandLinkButton_42")
        self.seriesList_42.addWidget(self.commandLinkButton_42, 6, 0, 1, 4)
        self.tabWidget.addTab(self.tabWidgetPage1, "")
        self.tabWidgetPage2 = QtWidgets.QWidget()
        self.tabWidgetPage2.setObjectName("tabWidgetPage2")
        self.gridLayoutWidget_23 = QtWidgets.QWidget(self.tabWidgetPage2)
        self.gridLayoutWidget_23.setGeometry(QtCore.QRect(10, 20, 370, 251))
        self.gridLayoutWidget_23.setObjectName("gridLayoutWidget_23")
        self.seriesList_43 = QtWidgets.QGridLayout(self.gridLayoutWidget_23)
        self.seriesList_43.setContentsMargins(0, 0, 0, 0)
        self.seriesList_43.setObjectName("seriesList_43")
        self.label_256 = QtWidgets.QLabel(self.gridLayoutWidget_23)
        self.label_256.setObjectName("label_256")
        self.seriesList_43.addWidget(self.label_256, 0, 0, 1, 4)
        self.pushButton_440 = QtWidgets.QPushButton(self.gridLayoutWidget_23)
        self.pushButton_440.setObjectName("pushButton_440")
        self.seriesList_43.addWidget(self.pushButton_440, 5, 2, 1, 1)
        self.pushButton_441 = QtWidgets.QPushButton(self.gridLayoutWidget_23)
        self.pushButton_441.setObjectName("pushButton_441")
        self.seriesList_43.addWidget(self.pushButton_441, 2, 2, 1, 1)
        self.pushButton_442 = QtWidgets.QPushButton(self.gridLayoutWidget_23)
        self.pushButton_442.setObjectName("pushButton_442")
        self.seriesList_43.addWidget(self.pushButton_442, 3, 2, 1, 1)
        self.pushButton_443 = QtWidgets.QPushButton(self.gridLayoutWidget_23)
        self.pushButton_443.setObjectName("pushButton_443")
        self.seriesList_43.addWidget(self.pushButton_443, 4, 2, 1, 1)
        self.pushButton_444 = QtWidgets.QPushButton(self.gridLayoutWidget_23)
        self.pushButton_444.setObjectName("pushButton_444")
        self.seriesList_43.addWidget(self.pushButton_444, 2, 3, 1, 1)
        self.pushButton_445 = QtWidgets.QPushButton(self.gridLayoutWidget_23)
        self.pushButton_445.setObjectName("pushButton_445")
        self.seriesList_43.addWidget(self.pushButton_445, 4, 3, 1, 1)
        self.pushButton_446 = QtWidgets.QPushButton(self.gridLayoutWidget_23)
        self.pushButton_446.setObjectName("pushButton_446")
        self.seriesList_43.addWidget(self.pushButton_446, 3, 3, 1, 1)
        self.pushButton_447 = QtWidgets.QPushButton(self.gridLayoutWidget_23)
        self.pushButton_447.setObjectName("pushButton_447")
        self.seriesList_43.addWidget(self.pushButton_447, 5, 3, 1, 1)
        self.pushButton_448 = QtWidgets.QPushButton(self.gridLayoutWidget_23)
        self.pushButton_448.setObjectName("pushButton_448")
        self.seriesList_43.addWidget(self.pushButton_448, 1, 3, 1, 1)
        self.label_257 = QtWidgets.QLabel(self.gridLayoutWidget_23)
        self.label_257.setObjectName("label_257")
        self.seriesList_43.addWidget(self.label_257, 3, 1, 1, 1)
        self.buttonInfo_43 = QtWidgets.QPushButton(self.gridLayoutWidget_23)
        self.buttonInfo_43.setObjectName("buttonInfo_43")
        self.seriesList_43.addWidget(self.buttonInfo_43, 1, 2, 1, 1)
        self.seriesPhoto_43 = QtWidgets.QLabel(self.gridLayoutWidget_23)
        self.seriesPhoto_43.setMaximumSize(QtCore.QSize(100, 100))
        self.seriesPhoto_43.setText("")
        self.seriesPhoto_43.setPixmap(QtGui.QPixmap("C:/Users/DeadlyComputer/Desktop/photo/578211-gettyimages-542930526.jpg"))
        self.seriesPhoto_43.setScaledContents(True)
        self.seriesPhoto_43.setObjectName("seriesPhoto_43")
        self.seriesList_43.addWidget(self.seriesPhoto_43, 1, 0, 5, 1)
        self.item_43 = QtWidgets.QLabel(self.gridLayoutWidget_23)
        self.item_43.setObjectName("item_43")
        self.seriesList_43.addWidget(self.item_43, 1, 1, 1, 1)
        self.label_258 = QtWidgets.QLabel(self.gridLayoutWidget_23)
        self.label_258.setObjectName("label_258")
        self.seriesList_43.addWidget(self.label_258, 2, 1, 1, 1)
        self.label_259 = QtWidgets.QLabel(self.gridLayoutWidget_23)
        self.label_259.setObjectName("label_259")
        self.seriesList_43.addWidget(self.label_259, 5, 1, 1, 1)
        self.label_260 = QtWidgets.QLabel(self.gridLayoutWidget_23)
        self.label_260.setObjectName("label_260")
        self.seriesList_43.addWidget(self.label_260, 4, 1, 1, 1)
        self.commandLinkButton_43 = QtWidgets.QCommandLinkButton(self.gridLayoutWidget_23)
        self.commandLinkButton_43.setObjectName("commandLinkButton_43")
        self.seriesList_43.addWidget(self.commandLinkButton_43, 6, 0, 1, 4)
        self.gridLayoutWidget_24 = QtWidgets.QWidget(self.tabWidgetPage2)
        self.gridLayoutWidget_24.setGeometry(QtCore.QRect(400, 20, 370, 251))
        self.gridLayoutWidget_24.setObjectName("gridLayoutWidget_24")
        self.seriesList_44 = QtWidgets.QGridLayout(self.gridLayoutWidget_24)
        self.seriesList_44.setContentsMargins(0, 0, 0, 0)
        self.seriesList_44.setObjectName("seriesList_44")
        self.label_261 = QtWidgets.QLabel(self.gridLayoutWidget_24)
        self.label_261.setObjectName("label_261")
        self.seriesList_44.addWidget(self.label_261, 0, 0, 1, 4)
        self.pushButton_449 = QtWidgets.QPushButton(self.gridLayoutWidget_24)
        self.pushButton_449.setObjectName("pushButton_449")
        self.seriesList_44.addWidget(self.pushButton_449, 5, 2, 1, 1)
        self.pushButton_450 = QtWidgets.QPushButton(self.gridLayoutWidget_24)
        self.pushButton_450.setObjectName("pushButton_450")
        self.seriesList_44.addWidget(self.pushButton_450, 2, 2, 1, 1)
        self.pushButton_451 = QtWidgets.QPushButton(self.gridLayoutWidget_24)
        self.pushButton_451.setObjectName("pushButton_451")
        self.seriesList_44.addWidget(self.pushButton_451, 3, 2, 1, 1)
        self.pushButton_452 = QtWidgets.QPushButton(self.gridLayoutWidget_24)
        self.pushButton_452.setObjectName("pushButton_452")
        self.seriesList_44.addWidget(self.pushButton_452, 4, 2, 1, 1)
        self.pushButton_453 = QtWidgets.QPushButton(self.gridLayoutWidget_24)
        self.pushButton_453.setObjectName("pushButton_453")
        self.seriesList_44.addWidget(self.pushButton_453, 2, 3, 1, 1)
        self.pushButton_454 = QtWidgets.QPushButton(self.gridLayoutWidget_24)
        self.pushButton_454.setObjectName("pushButton_454")
        self.seriesList_44.addWidget(self.pushButton_454, 4, 3, 1, 1)
        self.pushButton_455 = QtWidgets.QPushButton(self.gridLayoutWidget_24)
        self.pushButton_455.setObjectName("pushButton_455")
        self.seriesList_44.addWidget(self.pushButton_455, 3, 3, 1, 1)
        self.pushButton_456 = QtWidgets.QPushButton(self.gridLayoutWidget_24)
        self.pushButton_456.setObjectName("pushButton_456")
        self.seriesList_44.addWidget(self.pushButton_456, 5, 3, 1, 1)
        self.pushButton_457 = QtWidgets.QPushButton(self.gridLayoutWidget_24)
        self.pushButton_457.setObjectName("pushButton_457")
        self.seriesList_44.addWidget(self.pushButton_457, 1, 3, 1, 1)
        self.label_262 = QtWidgets.QLabel(self.gridLayoutWidget_24)
        self.label_262.setObjectName("label_262")
        self.seriesList_44.addWidget(self.label_262, 3, 1, 1, 1)
        self.buttonInfo_44 = QtWidgets.QPushButton(self.gridLayoutWidget_24)
        self.buttonInfo_44.setObjectName("buttonInfo_44")
        self.seriesList_44.addWidget(self.buttonInfo_44, 1, 2, 1, 1)
        self.seriesPhoto_44 = QtWidgets.QLabel(self.gridLayoutWidget_24)
        self.seriesPhoto_44.setMaximumSize(QtCore.QSize(100, 100))
        self.seriesPhoto_44.setText("")
        self.seriesPhoto_44.setPixmap(QtGui.QPixmap("C:/Users/DeadlyComputer/Desktop/photo/578211-gettyimages-542930526.jpg"))
        self.seriesPhoto_44.setScaledContents(True)
        self.seriesPhoto_44.setObjectName("seriesPhoto_44")
        self.seriesList_44.addWidget(self.seriesPhoto_44, 1, 0, 5, 1)
        self.item_44 = QtWidgets.QLabel(self.gridLayoutWidget_24)
        self.item_44.setObjectName("item_44")
        self.seriesList_44.addWidget(self.item_44, 1, 1, 1, 1)
        self.label_263 = QtWidgets.QLabel(self.gridLayoutWidget_24)
        self.label_263.setObjectName("label_263")
        self.seriesList_44.addWidget(self.label_263, 2, 1, 1, 1)
        self.label_264 = QtWidgets.QLabel(self.gridLayoutWidget_24)
        self.label_264.setObjectName("label_264")
        self.seriesList_44.addWidget(self.label_264, 5, 1, 1, 1)
        self.label_265 = QtWidgets.QLabel(self.gridLayoutWidget_24)
        self.label_265.setObjectName("label_265")
        self.seriesList_44.addWidget(self.label_265, 4, 1, 1, 1)
        self.commandLinkButton_44 = QtWidgets.QCommandLinkButton(self.gridLayoutWidget_24)
        self.commandLinkButton_44.setObjectName("commandLinkButton_44")
        self.seriesList_44.addWidget(self.commandLinkButton_44, 6, 0, 1, 4)
        self.gridLayoutWidget_25 = QtWidgets.QWidget(self.tabWidgetPage2)
        self.gridLayoutWidget_25.setGeometry(QtCore.QRect(790, 20, 370, 251))
        self.gridLayoutWidget_25.setObjectName("gridLayoutWidget_25")
        self.seriesList_45 = QtWidgets.QGridLayout(self.gridLayoutWidget_25)
        self.seriesList_45.setContentsMargins(0, 0, 0, 0)
        self.seriesList_45.setObjectName("seriesList_45")
        self.label_266 = QtWidgets.QLabel(self.gridLayoutWidget_25)
        self.label_266.setObjectName("label_266")
        self.seriesList_45.addWidget(self.label_266, 0, 0, 1, 4)
        self.pushButton_458 = QtWidgets.QPushButton(self.gridLayoutWidget_25)
        self.pushButton_458.setObjectName("pushButton_458")
        self.seriesList_45.addWidget(self.pushButton_458, 5, 2, 1, 1)
        self.pushButton_459 = QtWidgets.QPushButton(self.gridLayoutWidget_25)
        self.pushButton_459.setObjectName("pushButton_459")
        self.seriesList_45.addWidget(self.pushButton_459, 2, 2, 1, 1)
        self.pushButton_460 = QtWidgets.QPushButton(self.gridLayoutWidget_25)
        self.pushButton_460.setObjectName("pushButton_460")
        self.seriesList_45.addWidget(self.pushButton_460, 3, 2, 1, 1)
        self.pushButton_461 = QtWidgets.QPushButton(self.gridLayoutWidget_25)
        self.pushButton_461.setObjectName("pushButton_461")
        self.seriesList_45.addWidget(self.pushButton_461, 4, 2, 1, 1)
        self.pushButton_462 = QtWidgets.QPushButton(self.gridLayoutWidget_25)
        self.pushButton_462.setObjectName("pushButton_462")
        self.seriesList_45.addWidget(self.pushButton_462, 2, 3, 1, 1)
        self.pushButton_463 = QtWidgets.QPushButton(self.gridLayoutWidget_25)
        self.pushButton_463.setObjectName("pushButton_463")
        self.seriesList_45.addWidget(self.pushButton_463, 4, 3, 1, 1)
        self.pushButton_464 = QtWidgets.QPushButton(self.gridLayoutWidget_25)
        self.pushButton_464.setObjectName("pushButton_464")
        self.seriesList_45.addWidget(self.pushButton_464, 3, 3, 1, 1)
        self.pushButton_465 = QtWidgets.QPushButton(self.gridLayoutWidget_25)
        self.pushButton_465.setObjectName("pushButton_465")
        self.seriesList_45.addWidget(self.pushButton_465, 5, 3, 1, 1)
        self.pushButton_466 = QtWidgets.QPushButton(self.gridLayoutWidget_25)
        self.pushButton_466.setObjectName("pushButton_466")
        self.seriesList_45.addWidget(self.pushButton_466, 1, 3, 1, 1)
        self.label_267 = QtWidgets.QLabel(self.gridLayoutWidget_25)
        self.label_267.setObjectName("label_267")
        self.seriesList_45.addWidget(self.label_267, 3, 1, 1, 1)
        self.buttonInfo_45 = QtWidgets.QPushButton(self.gridLayoutWidget_25)
        self.buttonInfo_45.setObjectName("buttonInfo_45")
        self.seriesList_45.addWidget(self.buttonInfo_45, 1, 2, 1, 1)
        self.seriesPhoto_45 = QtWidgets.QLabel(self.gridLayoutWidget_25)
        self.seriesPhoto_45.setMaximumSize(QtCore.QSize(100, 100))
        self.seriesPhoto_45.setText("")
        self.seriesPhoto_45.setPixmap(QtGui.QPixmap("C:/Users/DeadlyComputer/Desktop/photo/578211-gettyimages-542930526.jpg"))
        self.seriesPhoto_45.setScaledContents(True)
        self.seriesPhoto_45.setObjectName("seriesPhoto_45")
        self.seriesList_45.addWidget(self.seriesPhoto_45, 1, 0, 5, 1)
        self.item_45 = QtWidgets.QLabel(self.gridLayoutWidget_25)
        self.item_45.setObjectName("item_45")
        self.seriesList_45.addWidget(self.item_45, 1, 1, 1, 1)
        self.label_268 = QtWidgets.QLabel(self.gridLayoutWidget_25)
        self.label_268.setObjectName("label_268")
        self.seriesList_45.addWidget(self.label_268, 2, 1, 1, 1)
        self.label_269 = QtWidgets.QLabel(self.gridLayoutWidget_25)
        self.label_269.setObjectName("label_269")
        self.seriesList_45.addWidget(self.label_269, 5, 1, 1, 1)
        self.label_270 = QtWidgets.QLabel(self.gridLayoutWidget_25)
        self.label_270.setObjectName("label_270")
        self.seriesList_45.addWidget(self.label_270, 4, 1, 1, 1)
        self.commandLinkButton_45 = QtWidgets.QCommandLinkButton(self.gridLayoutWidget_25)
        self.commandLinkButton_45.setObjectName("commandLinkButton_45")
        self.seriesList_45.addWidget(self.commandLinkButton_45, 6, 0, 1, 4)
        self.gridLayoutWidget_26 = QtWidgets.QWidget(self.tabWidgetPage2)
        self.gridLayoutWidget_26.setGeometry(QtCore.QRect(1180, 20, 370, 251))
        self.gridLayoutWidget_26.setObjectName("gridLayoutWidget_26")
        self.seriesList_46 = QtWidgets.QGridLayout(self.gridLayoutWidget_26)
        self.seriesList_46.setContentsMargins(0, 0, 0, 0)
        self.seriesList_46.setObjectName("seriesList_46")
        self.label_271 = QtWidgets.QLabel(self.gridLayoutWidget_26)
        self.label_271.setObjectName("label_271")
        self.seriesList_46.addWidget(self.label_271, 0, 0, 1, 4)
        self.pushButton_467 = QtWidgets.QPushButton(self.gridLayoutWidget_26)
        self.pushButton_467.setObjectName("pushButton_467")
        self.seriesList_46.addWidget(self.pushButton_467, 5, 2, 1, 1)
        self.pushButton_468 = QtWidgets.QPushButton(self.gridLayoutWidget_26)
        self.pushButton_468.setObjectName("pushButton_468")
        self.seriesList_46.addWidget(self.pushButton_468, 2, 2, 1, 1)
        self.pushButton_469 = QtWidgets.QPushButton(self.gridLayoutWidget_26)
        self.pushButton_469.setObjectName("pushButton_469")
        self.seriesList_46.addWidget(self.pushButton_469, 3, 2, 1, 1)
        self.pushButton_470 = QtWidgets.QPushButton(self.gridLayoutWidget_26)
        self.pushButton_470.setObjectName("pushButton_470")
        self.seriesList_46.addWidget(self.pushButton_470, 4, 2, 1, 1)
        self.pushButton_471 = QtWidgets.QPushButton(self.gridLayoutWidget_26)
        self.pushButton_471.setObjectName("pushButton_471")
        self.seriesList_46.addWidget(self.pushButton_471, 2, 3, 1, 1)
        self.pushButton_472 = QtWidgets.QPushButton(self.gridLayoutWidget_26)
        self.pushButton_472.setObjectName("pushButton_472")
        self.seriesList_46.addWidget(self.pushButton_472, 4, 3, 1, 1)
        self.pushButton_473 = QtWidgets.QPushButton(self.gridLayoutWidget_26)
        self.pushButton_473.setObjectName("pushButton_473")
        self.seriesList_46.addWidget(self.pushButton_473, 3, 3, 1, 1)
        self.pushButton_474 = QtWidgets.QPushButton(self.gridLayoutWidget_26)
        self.pushButton_474.setObjectName("pushButton_474")
        self.seriesList_46.addWidget(self.pushButton_474, 5, 3, 1, 1)
        self.pushButton_475 = QtWidgets.QPushButton(self.gridLayoutWidget_26)
        self.pushButton_475.setObjectName("pushButton_475")
        self.seriesList_46.addWidget(self.pushButton_475, 1, 3, 1, 1)
        self.label_272 = QtWidgets.QLabel(self.gridLayoutWidget_26)
        self.label_272.setObjectName("label_272")
        self.seriesList_46.addWidget(self.label_272, 3, 1, 1, 1)
        self.buttonInfo_46 = QtWidgets.QPushButton(self.gridLayoutWidget_26)
        self.buttonInfo_46.setObjectName("buttonInfo_46")
        self.seriesList_46.addWidget(self.buttonInfo_46, 1, 2, 1, 1)
        self.seriesPhoto_46 = QtWidgets.QLabel(self.gridLayoutWidget_26)
        self.seriesPhoto_46.setMaximumSize(QtCore.QSize(100, 100))
        self.seriesPhoto_46.setText("")
        self.seriesPhoto_46.setPixmap(QtGui.QPixmap("C:/Users/DeadlyComputer/Desktop/photo/578211-gettyimages-542930526.jpg"))
        self.seriesPhoto_46.setScaledContents(True)
        self.seriesPhoto_46.setObjectName("seriesPhoto_46")
        self.seriesList_46.addWidget(self.seriesPhoto_46, 1, 0, 5, 1)
        self.item_46 = QtWidgets.QLabel(self.gridLayoutWidget_26)
        self.item_46.setObjectName("item_46")
        self.seriesList_46.addWidget(self.item_46, 1, 1, 1, 1)
        self.label_273 = QtWidgets.QLabel(self.gridLayoutWidget_26)
        self.label_273.setObjectName("label_273")
        self.seriesList_46.addWidget(self.label_273, 2, 1, 1, 1)
        self.label_274 = QtWidgets.QLabel(self.gridLayoutWidget_26)
        self.label_274.setObjectName("label_274")
        self.seriesList_46.addWidget(self.label_274, 5, 1, 1, 1)
        self.label_275 = QtWidgets.QLabel(self.gridLayoutWidget_26)
        self.label_275.setObjectName("label_275")
        self.seriesList_46.addWidget(self.label_275, 4, 1, 1, 1)
        self.commandLinkButton_46 = QtWidgets.QCommandLinkButton(self.gridLayoutWidget_26)
        self.commandLinkButton_46.setObjectName("commandLinkButton_46")
        self.seriesList_46.addWidget(self.commandLinkButton_46, 6, 0, 1, 4)
        self.tabWidget.addTab(self.tabWidgetPage2, "")
        self.retranslateUi(self.obj)
        """
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(self.obj)


    def retranslateUi(self, StarList):
        _translate = QtCore.QCoreApplication.translate
        StarList.setWindowTitle(_translate("StarList", "Form"))
        self.label_225.setText(_translate("StarList", "TextLabel"))
        self.label_8.setText(_translate("StarList", "TextLabel"))
        self.label_11.setText(_translate("StarList", "TextLabel"))
        self.label_10.setText(_translate("StarList", "TextLabel"))
        self.label_13.setText(_translate("StarList", "TextLabel"))
        self.label_25.setText(_translate("StarList", "TextLabel"))
        self.label_224.setText(_translate("StarList", "TextLabel"))
        self.commandLinkButton.setText(_translate("StarList", "CommandLinkButton"))
        self.label_214.setText(_translate("StarList", "<html><head/><body><p align=\"center\">Series List</p></body></html>"))
        self.pushButton_368.setText(_translate("StarList", "PushButton"))
        self.pushButton_369.setText(_translate("StarList", "PushButton"))
        self.pushButton_370.setText(_translate("StarList", "PushButton"))
        self.pushButton_371.setText(_translate("StarList", "PushButton"))
        self.pushButton_372.setText(_translate("StarList", "PushButton"))
        self.pushButton_373.setText(_translate("StarList", "PushButton"))
        self.pushButton_374.setText(_translate("StarList", "PushButton"))
        self.pushButton_375.setText(_translate("StarList", "PushButton"))
        self.pushButton_376.setText(_translate("StarList", "PushButton"))
        self.label_215.setText(_translate("StarList", "TextLabel"))
        self.buttonInfo_35.setText(_translate("StarList", "info"))
        self.item_35.setText(_translate("StarList", "TextLabel"))
        self.label_216.setText(_translate("StarList", "TextLabel"))
        self.label_217.setText(_translate("StarList", "TextLabel"))
        self.label_218.setText(_translate("StarList", "TextLabel"))
        self.commandLinkButton_35.setText(_translate("StarList", "CommandLinkButton"))
        self.label_219.setText(_translate("StarList", "<html><head/><body><p align=\"center\">Series List</p></body></html>"))
        self.pushButton_377.setText(_translate("StarList", "PushButton"))
        self.pushButton_378.setText(_translate("StarList", "PushButton"))
        self.pushButton_379.setText(_translate("StarList", "PushButton"))
        self.pushButton_380.setText(_translate("StarList", "PushButton"))
        self.pushButton_381.setText(_translate("StarList", "PushButton"))
        self.pushButton_382.setText(_translate("StarList", "PushButton"))
        self.pushButton_383.setText(_translate("StarList", "PushButton"))
        self.pushButton_384.setText(_translate("StarList", "PushButton"))
        self.pushButton_385.setText(_translate("StarList", "PushButton"))
        self.label_220.setText(_translate("StarList", "TextLabel"))
        self.buttonInfo_36.setText(_translate("StarList", "info"))
        self.item_36.setText(_translate("StarList", "TextLabel"))
        self.label_221.setText(_translate("StarList", "TextLabel"))
        self.label_222.setText(_translate("StarList", "TextLabel"))
        self.label_223.setText(_translate("StarList", "TextLabel"))
        self.commandLinkButton_36.setText(_translate("StarList", "CommandLinkButton"))
        self.label_226.setText(_translate("StarList", "<html><head/><body><p align=\"center\">Series List</p></body></html>"))
        self.pushButton_386.setText(_translate("StarList", "PushButton"))
        self.pushButton_387.setText(_translate("StarList", "PushButton"))
        self.pushButton_388.setText(_translate("StarList", "PushButton"))
        self.pushButton_389.setText(_translate("StarList", "PushButton"))
        self.pushButton_390.setText(_translate("StarList", "PushButton"))
        self.pushButton_391.setText(_translate("StarList", "PushButton"))
        self.pushButton_392.setText(_translate("StarList", "PushButton"))
        self.pushButton_393.setText(_translate("StarList", "PushButton"))
        self.pushButton_394.setText(_translate("StarList", "PushButton"))
        self.label_227.setText(_translate("StarList", "TextLabel"))
        self.buttonInfo_37.setText(_translate("StarList", "info"))
        self.item_37.setText(_translate("StarList", "TextLabel"))
        self.label_228.setText(_translate("StarList", "TextLabel"))
        self.label_229.setText(_translate("StarList", "TextLabel"))
        self.label_230.setText(_translate("StarList", "TextLabel"))
        self.commandLinkButton_37.setText(_translate("StarList", "CommandLinkButton"))
        self.label_231.setText(_translate("StarList", "<html><head/><body><p align=\"center\">Series List</p></body></html>"))
        self.pushButton_395.setText(_translate("StarList", "PushButton"))
        self.pushButton_396.setText(_translate("StarList", "PushButton"))
        self.pushButton_397.setText(_translate("StarList", "PushButton"))
        self.pushButton_398.setText(_translate("StarList", "PushButton"))
        self.pushButton_399.setText(_translate("StarList", "PushButton"))
        self.pushButton_400.setText(_translate("StarList", "PushButton"))
        self.pushButton_401.setText(_translate("StarList", "PushButton"))
        self.pushButton_402.setText(_translate("StarList", "PushButton"))
        self.pushButton_403.setText(_translate("StarList", "PushButton"))
        self.label_232.setText(_translate("StarList", "TextLabel"))
        self.buttonInfo_38.setText(_translate("StarList", "info"))
        self.item_38.setText(_translate("StarList", "TextLabel"))
        self.label_233.setText(_translate("StarList", "TextLabel"))
        self.label_234.setText(_translate("StarList", "TextLabel"))
        self.label_235.setText(_translate("StarList", "TextLabel"))
        self.commandLinkButton_38.setText(_translate("StarList", "CommandLinkButton"))
        self.label_236.setText(_translate("StarList", "<html><head/><body><p align=\"center\">Series List</p></body></html>"))
        self.pushButton_404.setText(_translate("StarList", "PushButton"))
        self.pushButton_405.setText(_translate("StarList", "PushButton"))
        self.pushButton_406.setText(_translate("StarList", "PushButton"))
        self.pushButton_407.setText(_translate("StarList", "PushButton"))
        self.pushButton_408.setText(_translate("StarList", "PushButton"))
        self.pushButton_409.setText(_translate("StarList", "PushButton"))
        self.pushButton_410.setText(_translate("StarList", "PushButton"))
        self.pushButton_411.setText(_translate("StarList", "PushButton"))
        self.pushButton_412.setText(_translate("StarList", "PushButton"))
        self.label_237.setText(_translate("StarList", "TextLabel"))
        self.buttonInfo_39.setText(_translate("StarList", "info"))
        self.item_39.setText(_translate("StarList", "TextLabel"))
        self.label_238.setText(_translate("StarList", "TextLabel"))
        self.label_239.setText(_translate("StarList", "TextLabel"))
        self.label_240.setText(_translate("StarList", "TextLabel"))
        self.commandLinkButton_39.setText(_translate("StarList", "CommandLinkButton"))
        self.label_241.setText(_translate("StarList", "<html><head/><body><p align=\"center\">Series List</p></body></html>"))
        self.pushButton_413.setText(_translate("StarList", "PushButton"))
        self.pushButton_414.setText(_translate("StarList", "PushButton"))
        self.pushButton_415.setText(_translate("StarList", "PushButton"))
        self.pushButton_416.setText(_translate("StarList", "PushButton"))
        self.pushButton_417.setText(_translate("StarList", "PushButton"))
        self.pushButton_418.setText(_translate("StarList", "PushButton"))
        self.pushButton_419.setText(_translate("StarList", "PushButton"))
        self.pushButton_420.setText(_translate("StarList", "PushButton"))
        self.pushButton_421.setText(_translate("StarList", "PushButton"))
        self.label_242.setText(_translate("StarList", "TextLabel"))
        self.buttonInfo_40.setText(_translate("StarList", "info"))
        self.item_40.setText(_translate("StarList", "TextLabel"))
        self.label_243.setText(_translate("StarList", "TextLabel"))
        self.label_244.setText(_translate("StarList", "TextLabel"))
        self.label_245.setText(_translate("StarList", "TextLabel"))
        self.commandLinkButton_40.setText(_translate("StarList", "CommandLinkButton"))
        self.label_246.setText(_translate("StarList", "<html><head/><body><p align=\"center\">Series List</p></body></html>"))
        self.pushButton_422.setText(_translate("StarList", "PushButton"))
        self.pushButton_423.setText(_translate("StarList", "PushButton"))
        self.pushButton_424.setText(_translate("StarList", "PushButton"))
        self.pushButton_425.setText(_translate("StarList", "PushButton"))
        self.pushButton_426.setText(_translate("StarList", "PushButton"))
        self.pushButton_427.setText(_translate("StarList", "PushButton"))
        self.pushButton_428.setText(_translate("StarList", "PushButton"))
        self.pushButton_429.setText(_translate("StarList", "PushButton"))
        self.pushButton_430.setText(_translate("StarList", "PushButton"))
        self.label_247.setText(_translate("StarList", "TextLabel"))
        self.buttonInfo_41.setText(_translate("StarList", "info"))
        self.item_41.setText(_translate("StarList", "TextLabel"))
        self.label_248.setText(_translate("StarList", "TextLabel"))
        self.label_249.setText(_translate("StarList", "TextLabel"))
        self.label_250.setText(_translate("StarList", "TextLabel"))
        self.commandLinkButton_41.setText(_translate("StarList", "CommandLinkButton"))
        self.label_251.setText(_translate("StarList", "<html><head/><body><p align=\"center\">Series List</p></body></html>"))
        self.pushButton_431.setText(_translate("StarList", "PushButton"))
        self.pushButton_432.setText(_translate("StarList", "PushButton"))
        self.pushButton_433.setText(_translate("StarList", "PushButton"))
        self.pushButton_434.setText(_translate("StarList", "PushButton"))
        self.pushButton_435.setText(_translate("StarList", "PushButton"))
        self.pushButton_436.setText(_translate("StarList", "PushButton"))
        self.pushButton_437.setText(_translate("StarList", "PushButton"))
        self.pushButton_438.setText(_translate("StarList", "PushButton"))
        self.pushButton_439.setText(_translate("StarList", "PushButton"))
        self.label_252.setText(_translate("StarList", "TextLabel"))
        self.buttonInfo_42.setText(_translate("StarList", "info"))
        self.item_42.setText(_translate("StarList", "TextLabel"))
        self.label_253.setText(_translate("StarList", "TextLabel"))
        self.label_254.setText(_translate("StarList", "TextLabel"))
        self.label_255.setText(_translate("StarList", "TextLabel"))
        self.commandLinkButton_42.setText(_translate("StarList", "CommandLinkButton"))
        self.label_256.setText(_translate("StarList", "<html><head/><body><p align=\"center\">Series List</p></body></html>"))
        self.pushButton_440.setText(_translate("StarList", "PushButton"))
        self.pushButton_441.setText(_translate("StarList", "PushButton"))
        self.pushButton_442.setText(_translate("StarList", "PushButton"))
        self.pushButton_443.setText(_translate("StarList", "PushButton"))
        self.pushButton_444.setText(_translate("StarList", "PushButton"))
        self.pushButton_445.setText(_translate("StarList", "PushButton"))
        self.pushButton_446.setText(_translate("StarList", "PushButton"))
        self.pushButton_447.setText(_translate("StarList", "PushButton"))
        self.pushButton_448.setText(_translate("StarList", "PushButton"))
        self.label_257.setText(_translate("StarList", "TextLabel"))
        self.buttonInfo_43.setText(_translate("StarList", "info"))
        self.item_43.setText(_translate("StarList", "TextLabel"))
        self.label_258.setText(_translate("StarList", "TextLabel"))
        self.label_259.setText(_translate("StarList", "TextLabel"))
        self.label_260.setText(_translate("StarList", "TextLabel"))
        self.commandLinkButton_43.setText(_translate("StarList", "CommandLinkButton"))
        self.label_261.setText(_translate("StarList", "<html><head/><body><p align=\"center\">Series List</p></body></html>"))
        self.pushButton_449.setText(_translate("StarList", "PushButton"))
        self.pushButton_450.setText(_translate("StarList", "PushButton"))
        self.pushButton_451.setText(_translate("StarList", "PushButton"))
        self.pushButton_452.setText(_translate("StarList", "PushButton"))
        self.pushButton_453.setText(_translate("StarList", "PushButton"))
        self.pushButton_454.setText(_translate("StarList", "PushButton"))
        self.pushButton_455.setText(_translate("StarList", "PushButton"))
        self.pushButton_456.setText(_translate("StarList", "PushButton"))
        self.pushButton_457.setText(_translate("StarList", "PushButton"))
        self.label_262.setText(_translate("StarList", "TextLabel"))
        self.buttonInfo_44.setText(_translate("StarList", "info"))
        self.item_44.setText(_translate("StarList", "TextLabel"))
        self.label_263.setText(_translate("StarList", "TextLabel"))
        self.label_264.setText(_translate("StarList", "TextLabel"))
        self.label_265.setText(_translate("StarList", "TextLabel"))
        self.commandLinkButton_44.setText(_translate("StarList", "CommandLinkButton"))
        self.label_266.setText(_translate("StarList", "<html><head/><body><p align=\"center\">Series List</p></body></html>"))
        self.pushButton_458.setText(_translate("StarList", "PushButton"))
        self.pushButton_459.setText(_translate("StarList", "PushButton"))
        self.pushButton_460.setText(_translate("StarList", "PushButton"))
        self.pushButton_461.setText(_translate("StarList", "PushButton"))
        self.pushButton_462.setText(_translate("StarList", "PushButton"))
        self.pushButton_463.setText(_translate("StarList", "PushButton"))
        self.pushButton_464.setText(_translate("StarList", "PushButton"))
        self.pushButton_465.setText(_translate("StarList", "PushButton"))
        self.pushButton_466.setText(_translate("StarList", "PushButton"))
        self.label_267.setText(_translate("StarList", "TextLabel"))
        self.buttonInfo_45.setText(_translate("StarList", "info"))
        self.item_45.setText(_translate("StarList", "TextLabel"))
        self.label_268.setText(_translate("StarList", "TextLabel"))
        self.label_269.setText(_translate("StarList", "TextLabel"))
        self.label_270.setText(_translate("StarList", "TextLabel"))
        self.commandLinkButton_45.setText(_translate("StarList", "CommandLinkButton"))
        self.label_271.setText(_translate("StarList", "<html><head/><body><p align=\"center\">Series List</p></body></html>"))
        self.pushButton_467.setText(_translate("StarList", "PushButton"))
        self.pushButton_468.setText(_translate("StarList", "PushButton"))
        self.pushButton_469.setText(_translate("StarList", "PushButton"))
        self.pushButton_470.setText(_translate("StarList", "PushButton"))
        self.pushButton_471.setText(_translate("StarList", "PushButton"))
        self.pushButton_472.setText(_translate("StarList", "PushButton"))
        self.pushButton_473.setText(_translate("StarList", "PushButton"))
        self.pushButton_474.setText(_translate("StarList", "PushButton"))
        self.pushButton_475.setText(_translate("StarList", "PushButton"))
        self.label_272.setText(_translate("StarList", "TextLabel"))
        self.buttonInfo_46.setText(_translate("StarList", "info"))
        self.item_46.setText(_translate("StarList", "TextLabel"))
        self.label_273.setText(_translate("StarList", "TextLabel"))
        self.label_274.setText(_translate("StarList", "TextLabel"))
        self.label_275.setText(_translate("StarList", "TextLabel"))
        self.commandLinkButton_46.setText(_translate("StarList", "CommandLinkButton"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ui = stars()
    ui.show()
    sys.exit(app.exec_())
